version: '2'
services:
    api:
        image: marcopeg/node
        tty: true
        volumes:
            - ./services/api:/usr/src/app
        ports:
            - 8081:8080
        entrypoint:
            - npm
            - run
            - dev:start

    frontend:
        image: marcopeg/node
        tty: true
        volumes:
            - ./services/frontend:/usr/src/app
        ports:
            - 8080:8080
        environment:
            - API_ROOT=http://localhost:8081
        entrypoint:
            - npm
            - run
            - start
